CREATE TABLE Students (
  Album INT NOT NULL,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Password VARCHAR(128) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Photo VARCHAR(50),
  IsAdmin BOOL DEFAULT FALSE,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Album),
  UNIQUE (Email)
);